/**
 * Seed brief: a one-click markdown export of the current run.
 * Screenshot-beautiful, argument-ready.
 */

import type { SimState } from '@/sim/state';
import { VITAMIN_IDS, VITAMIN_LABELS } from '@/sim/ids';
import { SITES } from '@/data/sites';
import { TEMPLATES } from '@/data/templates';
import { capacityMassKg } from '@/sim/step';
import { constantValue } from '@/sim/constants';

/** Latest projected doubling time from history, or null when diverging. */
export function currentDoublingTimeSols(state: SimState): number | null {
  for (let i = state.history.length - 1; i >= 0; i -= 1) {
    const snap = state.history[i];
    if (snap.doublingTimeSols !== null) {
      // Only trust the most recent snapshot; older values are stale.
      return i === state.history.length - 1 ? snap.doublingTimeSols : null;
    }
    break;
  }
  return null;
}

/** Import kg during the current (in-progress) doubling. */
export function importKgThisDoubling(state: SimState): number {
  return state.importedKgCum - state.importedKgAtLastDoubling;
}

/** Whether the staged child could wake right now if completed. */
export function childCanWakeSoon(state: SimState): boolean {
  return state.child.completionFraction > 0.95;
}

/** Render the full markdown seed brief. */
export function renderSeedBrief(state: SimState): string {
  const site = SITES[state.siteId];
  const template = TEMPLATES[state.templateId];
  const unit = state.siteId === 'mars' ? 'sols' : 'days';
  const doubling = currentDoublingTimeSols(state);
  const working = state.robots.filter((r) => r.status === 'working' || r.status === 'idle').length;
  const broken = state.robots.filter((r) => r.status === 'broken').length;
  const uptime = state.robots.length > 0 ? working / state.robots.length : 0;
  const capacity = capacityMassKg(state);
  const lastDoubling = state.doublings.length > 0 ? state.doublings[state.doublings.length - 1] : null;

  const vitaminLines = VITAMIN_IDS.map(
    (v) => `| ${VITAMIN_LABELS[v]} | ${state.vitaminsKg[v].toFixed(0)} kg |`,
  ).join('\n');

  const doublingLines =
    state.doublings.length === 0
      ? '_No doublings yet._'
      : state.doublings
          .map((d) => `| ×${d.multiple} | ${unit === 'sols' ? 'sol' : 'day'} ${Math.floor(d.sol)} | ${Math.round(d.importKgSinceLast)} kg |`)
          .join('\n');

  return `# SEED BRIEF — ${site.name}

> The only score that matters: how fast machines build the machines.

| Metric | Value |
| --- | --- |
| Site | ${site.name} |
| Cargo template | ${template.name} (${state.payloadMassT} t landed) |
| ${unit === 'sols' ? 'Sol' : 'Day'} | ${Math.floor(state.sol)} |
| Generation | ${state.generation} |
| Active seeds | ${state.activeSeedCount} |
| **Doubling time** | **${doubling === null ? 'DIVERGING (∞)' : `${doubling.toFixed(0)} ${unit}`}** |
| Industrial capacity | ${(capacity / 1000).toFixed(1)} t (baseline ${(state.capacityBaselineKg / 1000).toFixed(1)} t) |
| Import mass, current doubling | ${importKgThisDoubling(state).toFixed(0)} kg |
| Import mass, last completed doubling | ${lastDoubling ? `${Math.round(lastDoubling.importKgSinceLast)} kg` : 'n/a'} |
| Robots (able / broken) | ${working} / ${broken} |
| Robot fleet uptime | ${(uptime * 100).toFixed(0)}% |
| Power (nameplate) | ${(state.energy.solarMassKg * constantValue('solarSpecificPowerKwPerKg')).toFixed(0)} kWe-class |
| Battery | ${state.energy.batteryKwh.toFixed(0)} / ${state.energy.batteryCapacityKwh.toFixed(0)} kWh |
| Child completion | ${(state.child.completionFraction * 100).toFixed(0)}% |
| Child can wake | ${childCanWakeSoon(state) ? 'YES — spec nearly met' : 'not yet'} |
| Mass ledger closure error | ${(state.massClosureError * 100).toFixed(2)}% |

## Vitamins remaining (imported precision mass)

| Bin | Stock |
| --- | --- |
${vitaminLines}

## Doublings

| Multiple | When | Import mass |
| --- | --- | --- |
${doublingLines}

## Status

${state.endState === null ? 'Run in progress.' : `End state: **${state.endState}**.`}
${state.events.length > 0 ? `Last event: _${state.events[state.events.length - 1].message}_` : ''}

---
_Generated by SEED — a first-principles simulator of a self-replicating factory. Numbers are conservative and cited; assumptions are labeled ASSUMED in-app._
`;
}
